import waves from '../assets/img/lb-waves.png';
import cwcLogo from "../assets/img/arthBanner.png"
import bikeImage from "../assets/img/bike.png";
import drawerIcon from "../assets/img/drawer_icon.png";
import profileIcon from "../assets/img/profile.png";
import downArrow from "../assets/img/downArrow.png";
import upArrow from "../assets/img/upArrow.png";
import rightArrow from "../assets/img/rightArrow.png";
import verifyTick from "../assets/img/verified.png";
import imagePlaceholder from "../assets/img/imagePlaceholder.png";
import bluePlusIcon from "../assets/img/bluePlus.png";
import minusIcon from "../assets/img/minusIcon.png";
import plusButton from "../assets/img/plusIcon.png";
import humanHappy from "../assets/img/humanhappy.png";
import logo from "../assets/img/logo.png";
import deleteButton from "../assets/img/deleteButton.png";
import placeholderImage from "../assets/img/placeholderImage.png";
import uploadImagePDF from "../assets/img/uploadImagePDF.png";
import arrowDown from "../assets/img/arrow-down.png";
import attachmentImage from "../assets/img/attachment.png";
import noData from "../assets/img/empty.png";

export const WAVES = waves;
export const CWC_LOGO = cwcLogo;
export const BIKE_IMAGE = bikeImage;
export const DRAWER_ICON = drawerIcon;
export const PROFILE_ICON = profileIcon;
export const DOWN_ARROW = downArrow;
export const NO_DATA = noData;
export const UP_ARROW = upArrow;
export const RIGHT_ARROW = rightArrow;
export const VERIFIED_TICK = verifyTick;
export const IMAGE_PLACEHOLDER = imagePlaceholder;
export const BLUE_PLUS_ICON = bluePlusIcon;
export const MINUS_ICON = minusIcon;
export const PLUS_BUTTON = plusButton;
export const HUMAN_HAPPY = humanHappy;
export const LOGO = logo;
export const DELETEBUTTON = deleteButton;
export const PLACEHOLDER_IMAGE = placeholderImage;
export const UPLOADIMAGEPDF = uploadImagePDF;
export const ARROW_DOWN = arrowDown;
export const ATTACHMENT = attachmentImage;