export const LOGIN_CONST = {
  HEADER: 'Welcome! \n(UAT)',
  EMAIL_ADDRESS: '@ Email Address',
  EMAIL_PLACEHOLDER: 'Enter Email Address',
  PASSWORD: '* Password',
  PASSWORD_PLACEHOLDER: 'Enter Password',
  BUTTON_TITLE: 'Login',
  RESET_PASSWORD: 'Forgot Password?',
  EMPTY_EMAIL_ID: 'Email address is mandatory',
  EMPTY_PASSWORD: 'Password is mandatory',
  VALID_EMAIL_ID: 'Invalid email address',
  VALID_PASSWORD: 'Invalid password',
};

export const DASHBOARD_CONST = {
  HEADER: 'My Dashboard',
};

export const LEAD_LIST_CONST = {
  HEADER: 'Lead Management',
  BUTTON_TITLE: 'Add\nLead',
  EDIT: 'Edit',
  UPDATEPROFILE: 'Update Profile',
  PLACEHOLDER_SEARCHBAR_LEAD: 'Search Lead',
  PLACEHOLDER_SEARCHBAR: 'Search Prospect',

};

export const ADD_LEAD_CONST = {
  HEADER: 'Add Lead - Electric Two Wheeler',
  LABEL_PAN_NUMBER: 'PAN Number*',
  SOURCE_TYPE_LABEL: 'Source Type',
  SOURCE_NAME_LABEL: 'Source Name',
  BRANCH_NAME_LABEL: 'Branch Name',
  REFERENCE_TYPE_LABEL: 'Reference Type',
  PLACEHOLDER_CIFID: 'CIF ID',
  PLACEHOLDER_MOBILE: 'Mobile Number*',
  PLACEHOLDER_EMAIL: 'Email Address*',
  PLACEHOLDER_PINCODE: 'Pincode*',
  BUTTON_TITLE: 'Save',
  BUTTON_TITLE_CANCEL: 'Cancel',
  PLACEHOLDER_FIRST_NAME: 'First Name*',
  PLACEHOLDER_MIDDLE_NAME: 'Middle Name',
  PLACEHOLDER_LAST_NAME: 'Last Name*',
  PLACEHOLDER_DROPDOWN_DEALER: 'Dealer*',
  PLACEHOLDER_DROPDOWN_DSA: 'DSA*',
  PLACEHOLDER_NAME: 'Name*',
  MANDATORY_CUSTOMER_NAME: 'First Name is mandatory',
  VALID_CUSTOMER_NAME: 'Invalid First Name',
  VALID_MIDDLE_NAME: 'Invalid Middle Name',
  MANDATORY_LAST_NAME: 'Last Name is mandatory',
  VALID_LAST_NAME: 'Invalid Last Name',
  MANDATORY_EMAIL: 'Email address is mandatory',
  VALID_EMAIL: 'Invalid Email address',
  MANDATORY_PAN: 'Pan Number is mandatory',
  VALID_PAN: 'Invalid Pan Number',
  MANDATORY_PHONE: 'Mobile Number is mandatory',
  VALID_PHONE: 'Invalid Mobile Number',
  MANDATORY_PINCODE: 'Pincode is mandatory',
  VALID_PINCODE: 'Invalid Pincode',
  PLACEHOLDER_DROPDOWN_BRANCH: 'Branch*',
  PLACEHOLDER_DROPDOWN_BRANCHS: ""
};

export const CONSENT_PENDING_CONST = {
  HEADER: 'Consent Pending',
  SOURCE_TYPE_LABEL: 'Source Type',
  SOURCE_TYPE_VALUE: 'DSA',
  REFERENCE_TYPE_LABEL: 'Reference Type',
  BUTTON_TITLE_PROCEED: 'Proceed',
  BUTTON_TITLE_CANCEL: 'Cancel',
  SELECT_MODE_LABEL: 'Select mode of verification',
  BUTTON_TITLE_DELETE: 'Delete',
  BUTTON_TITLE_EDIT: 'Edit',
  SELECT_MODE_LABEL: 'Select mode of verification',
  DEALER_NAME: 'Dealer Name',
  DEALER_NAME_FIELD: 'DSA2',
  CUSTOMER_NAME: 'Customer Name',
  FIRST_NAME: 'First Name',
  MIDDLE_NAME: 'Middle Name',
  LAST_NAME: 'Last Name',
  CUSTOMER_NAME_FIELD: 'XYZ',
  MOBILE_NUMBER: 'Mobile Number',
  MOBILE_NUMBER_FIELD: '9845612345',
  EMAIL: 'Email',
  EMAIL_FIELD: 'amit@gmailcom',
  PINCODE: 'Pincode',
  PINCODE_FIELD: '400703',
  PLACEHOLDER_DROPDOWN_DEALER: 'Dealer',
  PLACEHOLDER_DROPDOWN_DSA: 'DSA Name',
  BRANCH_NAME: 'Branch Name',
};

export const EDIT_CONST = {
  HEADER: 'Edit Lead',
  SOURCE_TYPE_LABEL: 'Source Type',
  SOURCE_TYPE_VALUE: 'DSA',
  REFERENCE_TYPE_LABEL: 'Reference Type',
  BUTTON_TITLE_SAVE: 'Save',
  BUTTON_TITLE_CANCEL: 'Cancel',
  BUTTON_TITLE_DELETE: 'Delete',
  BUTTON_TITLE_EDIT: 'Edit',
  SELECT_MODE_LABEL: 'Select mode of verification',
  DEALER_NAME: 'Dealer Name',
  DEALER_NAME_FIELD: 'DSA2',
  CUSTOMER_NAME: 'Customer Name*',
  FIRST_NAME: 'First Name*',
  MIDDLE_NAME: 'Middle Name',
  LAST_NAME: 'Last Name*',
  CUSTOMER_NAME_FIELD: 'XYZ',
  MOBILE_NUMBER: 'Mobile Number*',
  MOBILE_NUMBER_FIELD: '9845612345',
  EMAIL: 'Email*',
  EMAIL_FIELD: 'amit@gmailcom',
  PINCODE: 'Pincode*',
  PINCODE_FIELD: '400703',
  PLACEHOLDER_DROPDOWN_DEALER: 'Dealer*',
  PLACEHOLDER_DROPDOWN_DSA: 'DSA Name*',
  MANDATORY_CUSTOMER_NAME: 'Customer Name is mandatory',
  VALID_CUSTOMER_NAME: 'Invalid Customer Name',
  MANDATORY_FIRST_NAME: 'First Name is mandatory',
  VALID_FIRST_NAME: 'Invalid First Name',
  VALID_MIDDLE_NAME: 'Invalid Middle Name',
  MANDATORY_LAST_NAME: 'Last Name is mandatory',
  VALID_LAST_NAME: 'Invalid Last Name',
  MANDATORY_EMAIL: 'Email address is mandatory',
  VALID_EMAIL: 'Invalid Email address',
  MANDATORY_PHONE: 'Mobile Number is mandatory',
  MANDATORY_PAN: 'Pan Number is mandatory',
  VALID_PAN: 'Invalid Pan Number',
  VALID_PHONE: 'Invalid Mobile Number',
  MANDATORY_PINCODE: 'Pincode is mandatory',
  VALID_PINCODE: 'Invalid Pincode',
};

export const OTPVERIFICATION_CONST = {
  HEADER: 'OTP Verification',
  BUTTON_TITLE_PROCEED: 'Proceed',
  BUTTON_TITLE_CANCEL: 'Cancel',
  ENTEROTP: 'Enter OTP',
  SENTOTP: 'An OTP has been sent to 98XXXXXX73',
};

export const VERIFICATION_CONST = {
  HEADER: 'Verification',
  BUTTON_TITLE_VERIFY: 'Verify',
  BUTTON_TITLE_BACK: 'Back',
  CUSTOMER_NAME: 'Customer Name',
  CUSTOMER_NAME_FIELD: 'XYZ',
  MOBILE_NUMBER: 'Mobile Number',
  MOBILE_NUMBER_FIELD: '9845612345',
  EMAIL: 'Email Address',
  EMAIL_FIELD: 'amit@gmailcom',
  TEXT_CONSENTREQUEST:
    'Consent request link sent on your email address and mobile number',
  //    'Consent request link sent An OTP has been sent on your email address and mobile number',
};

export const BUSINESSDETAILS_CONST = {
  HEADER: 'Quick Data Entry',
  PLACEHOLDER_DROPDOWN_SECTOR: 'Please select Sector',
  PLACEHOLDER_DROPDOWN_INDUSTRY: 'Please select Industry',
  PLACEHOLDER_DROPDOWN_SUBINDUSTRY: 'Please select Sub-Industry',
  PLACEHOLDER_DROPDOWN_SEGMENT: 'Please select Segment',
  PLACEHOLDER_DROPDOWN_ACCOUNTTPE: 'Please select Account type',
  PLACEHOLDER_TEXTINPUT_CIN: 'CIN',
  MANDATORY_TURNOVER: 'Turnover is mandatory',
  INVALID_TURNOVER: 'Invalid input',
  PLACEHOLDER_TEXTINPUT_TURNOVER: 'Turnover',
  MANDATORY_NETWORTH: 'Monthly Income is mandatory',
  MANDATORY_ACCOUNTNUMBER: 'Account Number is mandatory',
  MANDATORY_IFSC: 'IFSC Code is mandatory',
  MANDATORY_BANKNAME: 'Bank Name is mandatory',
  INVALID_NETWORTH: 'Invalid input',
  PLACEHOLDER_TEXTINPUT_NETWORTH: 'Monthly Income(in ₹)',
  PLACEHOLDER_TEXTINPUT_ACCOUNTNUMBER: 'Account Number*',
  PLACEHOLDER_TEXTINPUT_IFSC: 'IFSC Code*  ',
  PLACEHOLDER_TEXTINPUT_BANKNAME: 'Bank Name*  ',
  BUTTON_SAVEEXIT: 'Cancel',
  BUTTON_NEXT: 'Save',
  BUTTON_TITLE_NEXT: 'Next',

};

export const LOANDETAILS_CONST = {
  HEADER: 'Quick Data Entry',
  PLACEHOLDER_DROPDOWN_VEHICLE: 'Please select Vehicle',
  PLACEHOLDER_DROPDOWN_BRANDOFVEHICLE: 'Please select Brand of Vehicle',
  PLACEHOLDER_DROPDOWN_MODEL: 'Please select Model',
  PLACEHOLDER_DROPDOWN_SUBMODEL: 'Please select Sub-Model',
  PLACEHOLDER_DROPDOWN_DEALER: 'Please select Dealer',
  PLACEHOLDER_DROPDOWN_SUBDEALER: 'Please select Sub-Dealer',
  PLACEHOLDER_TEXTINPUT_CIN: 'CIN',
  PLACEHOLDER_TEXTINPUT_TURNOVER: 'Turnover',
  PLACEHOLDER_TEXTINPUT_NETWORTH: 'Net Worth',
  BUTTON_SAVEEXIT: 'Cancel',
  BUTTON_NEXT: 'Save',
  BUTTON_EMI: 'Calculate EMI',
  BUTTON_TITLE_NEXT: 'Next',
  ROI: 'Rate of Interest% *',
  MANDATORY_ROI: 'Rate of interest field is mandatory',
  VALID_ROI: 'Invalid Number',
  LIFE_INSURANCE: 'Is Life Insurance taken?*',
  LOANPROTECT: 'Loan Protect Insurance',
  PREMIUMAMOUT: 'Premium Amount:',
  OPDPREMIUMAMOUT: 'OPD Premium Amount:',
  NAMENOMINEE: 'Name*',
  ADDRESS: 'Address*',
  DOB: 'Date of Birth*',
  INVALID_DATE_OF_BIRTH: 'Invalid Date of birth',
  DEALERCHARGES: 'Dealer Charges*',
  PROCESSINGFEES: 'Processing Fees*',
  INSURANCEAMOUNT: 'Insurance Amount*',
  BUREAUECHARGES: 'Bureau Charges*',
  STAMPDUTY: 'Stamp Duty*',
  DEALERPAYOUT: 'Dealer Payout*',
  OTHERCHARGES: 'Other Charges*',
  MANDATORY_DEALERCHARGES: 'Dealer Charges is mandatory',
  VALID_DEALERCHARGES: 'Invalid Dealer Charges',
  MANDATORY_PROCESSINGFEES: 'Processing Fees is Mandatory',
  VALID_PROCESSINGFEES: 'Invalid Processing Fees',
  MANDATORY_INSURANCEAMOUNT: 'Insurance Amount is Mandatory',
  VALID_INSURANCEAMOUNT: 'Invalid Insurance Amount',
  MANDATORY_BUREAUCHARGES: 'Bureau Charges is Mandatory',
  VALID_BUREAUCHARGES: 'Invalid Bureau Charges',
  MANDATORY_OTHERCHARGES: 'Other Charges is Mandatory',
  VALID_OTHERCHARGES: 'Invalid Other Charges',
  MANDATORY_PREMIUMAMOUNT: 'Premium Amount is Mandatory',
  VALID_PREMIUMAMOUNT: 'Invalid Premium Amount',
  MANDATORY_NAMENOMINEE: 'Name is Mandatory',
  VALID_NAMENOMINEE: 'Invalid Name format',
  MANDATORY_DATEOFBIRTH: 'Date of birth is mandatory',
  MANDATORY_ADDRESS: 'Address is mandatory',
  MANDATORY_RELATION: 'Relation is mandatory',
  DEALERSUBVENTION: 'Dealer Subvention*',
  EXSHOWROOM: 'Ex-Showroom Price*',
  INSURANCE: 'Insurance Amount*',
  ADMINFEES: 'Admin Fees*',
  NACHCHARGES: 'NACH Charges*',
  PREEMI: 'Pre EMI*',
  PDDCHARGES: 'PDD Charges*',
  CONVENIENCECHARGES: 'Convenience Charges*',
  MANDATORY_DEALERSUBVENTION: 'Dealer Subvention Mandatory',
  VALID_DEALERSUBVENTION: 'Invalid Dealer Subvention',
  MANDATORY_EXSHOWROOM: 'Ex Showroom Price is Mandatory',
  VALID_EXSHOWROOM: 'Invalid Ex Showroom Price',
  MANDATORY_INSURNCE: 'Insurance Amount is Mandatory',
  VALID_INSURNCE: 'Invalid Insurance Amount',
  MANDATORY_ADMIN: 'Admin Fees Mandatory',
  VALID_ADMIN: 'Invalid Admin Fees',
  MANDATORY_NACH: 'NACH Charges Mandatory',
  VALID_NACH: 'Invalid NACH Charges',
  MANDATORY_PREEMI: 'Pre EMI Mandatory',
  VALID_PREEMI: 'Invalid Pre EMI Value',
  MANDATORY_PDD: 'PDD Charges Mandatory',
  VALID_PDD: 'Invalid PDD Charges',
  MANDATORY_CONVENIENCE: 'Convenience Charges Mandatory',
  VALID_CONVENIENCE: 'Invalid Convenience Charges',
  MANDATORY_STAMP: 'Stamp Duty Mandatory',
  VALID_STAMP: 'Invalid Stamp Duty',
  MANDATORY_DEALERPAYOUT: 'Dealer Payout Mandatory',
  VALID_DEALERPAYOUT: 'Invalid Dealer Payout',
  PLACEHOLDER_DROPDOWN_DEALERPAYOUT: "Dealer Payout Type"
};

export const PAN_GST_CONST = {
  HEADER: 'Quick Data Entry',
  PAN_GST_LABEL: 'PAN & GST Verification',
  ENTITY_TYPE: 'Customer Type',
  OCCUPATION_TYPE: 'Occupation Type',
  PAN_INDIVIDUAL: 'Individual',
  PAN_NON_INDIVIDUAL: 'Non Individual',
  OCCUPATION_SELF_EMPLOYEED: 'Self-Employeed',
  OCCUPATION_SALARIED: 'Salaried',
  OCCUPATION_SELF: 'Self-Employed',
  PLACEHOLDER_DROPDOWN: 'Entity',
  PAN_DETAILS: 'PAN Details',
  Form60_DETAILS: 'Form 60 Details',
  MANDATORY_LABEL: 'Mandatory',
  UPLOAD_PHTO: 'Upload\nPhoto',
  TAKE_PHOTO: 'Take a\nPhoto',
  LABEL_PAN_NUMBER: 'PAN Number*',
  LABEL_DATE: 'Date of Incorporation*',
  LABEL_NAME: 'Name*',
  BUTTON_TITLE_RESET: 'Reset',
  PLACEHOLDER_GST_DROPDOWN: 'GST',
  BUTTON_TITLE_VERIFY: 'Verify',
  BUTTON_TITLE_SAVE: 'Save',
  LABEL_DOB: 'Date of Birth*',
  OPTION_PAN: 'Pan',
  OPTION_FORM_60: 'Form 60',
  TEXT_VERIFIED: 'Verified',
  DOC_VALIDATION: 'Please upload valid document',
  MANDATORY_PAN_NAME: 'PAN name is mandatory',
  IVALID_PAN_NAME: 'Invalid PAN name',
  MANDATORY_Form_NAME: ' name is mandatory',
  IVALID_Form_NAME: 'Invalid  name',
  MANDATORY_GENDER: 'Gender is mandatory',
  MANDATORY_PAN_NUMBER: 'PAN number is mandatory',
  MADATORY_DATE_OF_INCORPORATION: 'Date of incorporation is mandatory',
  MADATORY_DATE_OF_BIRTH: 'Date of birth is mandatory',
  INVALID_PAN_NUMBER: 'Invalid PAN number',
  INVALID_DATE_OF_BIRTH: 'Invalid Date of birth',
  BUTTON_NEXT: 'Next',
  PLACEHOLDER_GENDER: 'Gender*',
};
export const ADDITIONAL_DETAILS_CONST = {
  HEADER: 'Quick Data Entry',
  ADDITIONAL_DETAIL_LABEL: 'Additional Details',
  REGISTERED_ADDRESS: 'Residential Address*',
  REGISTERED_ADDRESSIND: 'Registered Address*',
  REGISTERED_ADDRESS2: 'Residential Address',
  ADD_KYC_LABEL: 'Add KYC Document*',
  ADD_KYC_LABEL_COAPPLICANT: 'Add KYC Document',
  RESIDING_ADDRESS: 'Residing at Current Address since*',
  BUSINESS_ADDRESS: 'Residing at Current Address since*',
  WORKING_JOB_SINCE: 'Working at Current Job since*',
  FIRST_JOB: 'Is the current Job, your first job?',
  WORK_EXPERIENCE: 'Total Work Experience',
  ADHAR_CARD: 'Aadhar\nCard',
  PASSPORT: 'Passport',
  DRIVING_LICENSE: 'Driver’s\nLicense',
  OTHER_LABEL: 'Other',
  IMAGE_FRONT: 'Front',
  IMAGE_BACK: 'Back',
  RESIDENTIAL_ADDRESS: 'KYC address',
  ADDRESS_LINE_1: 'Address line 1*',
  ADDRESS_LINE_2: 'Address line 2',
  PINCODE: 'Pincode*',
  CITY: 'City*',
  STATE: 'State*',
  YEAR: 'Years*',
  MONTH: 'Months*',
  RESIDENT_TYPE: 'Residence Type*',
  OFFICE_TYPE: 'Current Residence Type *',
  BUTTON_TITLE_SAVE: 'Save',
  ADD_UTILITY_BILL: 'FI/CPV waiver document & Income Proof',
  UTILITY_BILL_FOR: 'FI/ CPV waiver for',
  CURRENT_ADDRESS: 'Current Addresss',
  PERMANENT_ADDRESS: 'Current Address*',
  PERMANENT_ADDRESS2: 'Current Address*',
  ADHAR_ID: 'Aadhar ID*',
  ADHAR_NAME: 'Aadhar Name*',
  INVALID_AADHAR_NUMBER: 'Invalid Aadhar Number',
  REQUIRED_AADHAR_NUMBER: 'Aadhar Number is required',

  INVALID_VPA: 'Invalid VPA',
  REQUIRED_VPA: 'VPA is required',

  INVALID_AADHAR_NAME: 'Invalid Aadhar Name',
  REQUIRED_AADHAR_NAME: 'Aadhar Name is required',

  REQUIRED_CITY_NAME: 'City Name is required',
  INVALID_CITY_NAME: 'Invalid City Name ',
  INVALID_STATE_NAME: 'Invalid State Name',
  FILE_NUMBER_PASSPORT: 'File Number*',
  REQUIRED_FILE_NUMBER: 'File Number is required',
  INVALID_FILE_NUMBER: 'Invalid File Number',
  REQUIRED_TELEPHONE_NUMBER: 'Telephone Number is required',
  INVALID_TELEPHONE_NUMBER: 'Invalid Telephone Number',
  DATE_OF_BIRTH: 'Date of birth*',
  INVALID_DOB: 'Invalid Date of Birth',
  DL_NO: 'DL No*',
  INVALID_DL_NUMBER: 'Invalid Driving license number',
  REQUIRED_DL_NUMBER: 'Driving license Number is required',
  BUTTON_VERIFY: 'Verify',
  ELECTRICITY_BILL: 'Electricity\nBill',
  GAS_BILL: 'Gas\nBill',
  LANDLINE_BILL: 'Landline\nBill',
  SELECT_OTHER: 'Select Other',
  RESIDENTIAL_ADDRESS2: 'Residential Address 2',
  BUTTON_GET_DETAILS: 'Get Details',
  CONSUMER_NUMBER: 'Consumer Number*',
  INVALID_CONSUMER_NUMBER: 'Invalid Consumer Number',
  REQUIRED_CONSUMER_NUMBER: 'Consumer Number is required',
  REQUIRED_LPG_NUMBER: 'LPG Number is required',
  INVALID_LPG_NUMBER: 'Invalid LPG Number',
  SERVICE_PROVIDER: 'Service Provider*',
  LABEL_LANDLINE_NUMBER: 'Landline Number*',
  PINCODE_VALIDATION: 'Invalid pincode',
  VOTER_ID: "Voter's ID",
  EPIC_NUMBER: 'Epic No*',
  REQUIRED_EPIC_NUMBER: 'Epic Number is required',
  INVALID_EPIC_NUMBER: 'Invalid Epic Number',
  INVALID_AADHAR_NUMBER: 'Invalid Aadhar Number',
  EMPLOYEMENT_DETAILS: 'Employment Details*',
  EMPLOYEMENT_DETAILS_COAPPLICANT: 'Employment Details',
  COMPANY_NAME: 'Company*',
  OTHER_INDUSTRY_NAME: 'Industry Name*',
  DESIGNATION: 'Designation*',
  COMPANY_TYPE: 'Company Type*',
  INDUSTRY: 'Industry*',
  PLACEHOLDER_EMAIL: 'Email Address*',
  MANDATORY_EMAIL: 'Email address is mandatory',
  VALID_EMAIL: 'Invalid Email address',
  OFFICE_ADDRESS: 'Office Address*',
  CURRENT_OFFICE_ADDRESS: 'Current Residence Address*',
  OFFICE_ADDRESS_COAPPLICANT: 'Office Address',
  ADDITIONAL_CONTACT_DETAILS: 'Additional Contact Details*',
  ADDITIONAL_CONTACT_DETAILS_COAPPLICANT: 'Additional Contact Details',
  MOBILE_NUMBER: 'Mobile Number',
  BUTTON_NEXT: 'Next',
  INVALID_MOBILE_NUMBER: 'Invalid mobile number',
  LPG_ID: 'LPG ID*',
  STD_CODE: 'STD Code*',
  TEXT_VERIFIED: 'Verified',
};

export const REFERENCES_CONST = {
  HEADER: 'Quick Data Entry',
  REFERENCES_LABEL: 'References',
  BUTTON_TITLE_SAVE: 'Save',
  BUTTON_TITLE_CANCEL: 'Cancel',
  FAMILY_REFERENCE: 'Family Reference*',
  NON_FAMILY_REFERENCE: 'Non-Family Reference*',
  PLACEHOLDER_DROPDOWN_FAMILY: 'Relationship*',
  MOBILE: 'Mobile Number*',
  NAME: 'Name*',
  ADDRESS: 'Address*',
  MANDATORY_NAME: 'Name is mandatory',
  VALID_NAME: 'Invalid Name',
  MANDATORY_PHONE: 'Mobile Number is mandatory',
  VALID_PHONE: 'Invalid Mobile Number',
  MANDATORY_ADDRESS: 'Address is mandatory',
  VALID_ADDRESS: 'Invalid address',
  NEXT_BUTTON: 'Next',
};

export const SCHEMES_CONST = {
  HEADER: 'Quick Data Entry',
  SCHEMES_LABEL: 'Schemes',
  BUTTON_TITLE_SAVE: 'Save',
  BUTTON_TITLE_NEXT: 'Submit',
};

export const QDESUCCESS_CONST = {
  HEADER: 'Congrats ',
  GREETDESCRIPTION:
    'You have successfully completed and have been verified in the Quick Data Entry Stage.',
  GREETDESCRIPTIONDDE:
    'You have successfully completed and have been verified in the Detailed Data Entry Stage.',
  GREET:
    'Your tentative loan offer has been generated. Final offer subject to credit decisioning.',
  GREETDDE:
    'You have successfully completed and have been verified in the Detailed Data Entry Stage.',
  GREETQDE:
    'You have successfully completed and have been verified in the Quick Data Entry Stage.',
  CUSTOMERID: 'Customer ID',
  APPLICATIONID: 'Application ID',
  LOANAMOUNT: 'Loan Amount',
  DURATIONOFLOAN: 'Duration of Loan',
  RATEOFINTEREST: 'Rate of Interest',
  EMIAMOUNT: 'EMI Amount',
  TEXT_JOURNEY: 'You are now halfway close to purchasing your two wheeler !',
  BUTTON_TITLE_ADD: 'Add Co-Applicant/Guarantor',
  BUTTON_TITLE_PROCEED: 'Proceed to DDE',
  BUTTON_TITLE_SUBMIT: 'Submit to Credit',
  BUTTON_CONTINUE_LATER: 'Continue Later',
  BUTTON_VIEW_AGREEMENT: 'View Agreement',
  BUTTON_OK: 'Ok',
  MANDATORY_ADDRESS: 'Comment field is mandatory',
  COMMENT: "Comment"
};

export const LOAN_SUMMARY_CONST = {
  HEADER: 'Loan Summary',
  BUTTON_CONTINUE: 'Continue',
  BUTTON_CONSENTPENDING: 'Consent Pending',
  BUTTON_LOANAGREEMENT: 'Loan Agreement',
  BUTTON_PREDISBURSAL: 'Pre Disbursal',
  BUTTON_REPAYMENT: 'Repayment',
  BUTTON_POSTDISBURSAL: 'Post Disbursal',
  BUTTON_LOANOFFER: 'View Loan Offer',
  EDIT_LABEL: 'edit',
  ADD_CO_APPLICANT: '+ Co-Applicant',
  ADD_GUARANTOR: '+ Guarantor',
};

export const BANKDETAILS_CONST = {
  HEADER: 'Detailed Data Entry',
  GOOGLEMANDATORY: '*Google address registred with Bank is required',
  PLACEHOLDER_DROPDOWN_BANK_NAME: 'Bank Name',
  EMAIL: 'Email Address',
  PASSWORD: 'Password',
  UPLOADSALARYSLIPS: 'Upload Salary Slips',
  BUTTON_TITLE_SAVEEXIT: 'Save',
  BUTTON_TITLE_RESENDLINK: 'Resend Link',
  BUTTON_TITLE_NEXT: 'Next',
  GET_BANK_DETAILS: 'Get Bank Details',
  GETTING_BANK_DETAILS: 'Getting Bank Details',
  FETCH: 'Fetch',
};

export const ITR_VERIFICATION_CONST = {
  HEADER: 'Detailed Data Entry',
  ITR_VERIFICATION: 'ITR Verification',
  LABEL_VERIFICATION_MOD: 'Verification Mode',
  LABEL_VERIFY_VIA_LINK: 'Via Link to Customer',
  LABEL_UPLOAD_ITR: 'Upload ITR Document (Pdf only)',
  BUTTON_NEXT: 'Submit',
  BUTTON_SAVE: 'Save',
  BUTTON_EMAIL: 'Send Link to Email',
  UPLOAD_ITR_TEXT: 'Upload ITR Document',
};

export const LOAN_AGREEMENT_CONST = {
  HEADER: 'Loan Agreement',
  AGREEMENT_LETTER: 'Agreement Letter',
  AGREEMENT_GREET: 'Loan Agreement eSigning and eStamping',
  BUTTON_PROCEED: 'Proceed',
  BUTTON_MAIN: 'Main-Applicant',
  BUTTON_CO_APP: 'Co-Applicant',
  BUTTON_GURANTOR: 'Gurantor',
  LOAN_AGREEMENT: 'Loan Agreement',
  BUTTON_DOWNLOAD_LOAN: 'Download Loan Agreement',
  BUTTON_UPLOAD_LOAN: 'Upload Signed Loan Agreement',
  BUTTON_CONTINUE_LATER: 'Continue Later',
  BUTTON_SUBMIT: 'Loan Summary',
  PLACEHOLDER_DROPDOWN_PATTERN: 'Signing Mode',
};

export const PERSONAL_DETAILS_CONST = {
  FATHERS_NAME: "Father's Name*",
  INVALID_FATHERS_NAME: "Invalid Father's Name",
  REQUIRED_FATHERS_NAME: "Father's Name is required",

  SPOUSE_NAME: "Spouse's Name*",
  INVALID_SPOUSE_NAME: "Invalid Spouse's Name",
  REQUIRED_SPOUSE_NAME: "Spouse's Name is required",

  MOTHERS_NAME: "Mother's Name*",
  INVALID_MOTHERS_NAME: "Invalid Mother's Name",
  REQUIRED_MOTHERS_NAME: "Mother's Name is required",

  MARATIAL_STATUS: 'Marital Status*',
  INVALID_MARATIAL_STATUS: 'Invalid Martial Status',
  REQUIRED_MARATIAL_STATUS: 'Martial Status is required',

  QUALIFICATION: 'Qualification*',
  REQUIRED_QUALIFICATION: 'Qualification is required',

  AADHAR_NUMBER: 'Aadhar Number*',
  INVALID_AADHAR_NUMBER: 'Invalid Aadhar Number',
  REQUIRED_AADHAR_NUMBER: 'Aadhar Number is required',

  RELATION_WITH_MAIN_APPLICANT: 'Relation with Main Applicant*',
  INVALID_RELATION: 'Invalid Relation with main applicant',
  REQUIRED_RELATION: 'Relation with Main Applicant is required',

  ANNUAL_GROSS_INCOME: 'Annual Gross Income*(in ₹)',
  INVALID_ANNUAL_GROSS_INCOME: 'Invalid Annual Gross Income',
  REQUIRED_ANNUAL_GROSS_INCOME: 'Annual Gross Income is required',

  NET_MONTHLY_INCOME: 'Net Monthly Income*(in ₹)',
  INVALID_NET_MONTHLY_INCOME: 'Invalid Net Monthly Income',
  REQUIRED_NET_MONTHLY_INCOME: 'Net Monthly Income is required',

  NET_MONTHLY_OBLIGATIONS: 'Net Monthly Obligations*(in ₹)',
  INVALID_NET_MONTHLY_OBLIGATIONS: 'Invalid Net Monthly Obligations',
  REEQUIRED_NET_MONTHLY_OBLIGATIONS: 'Net Monthly Obligations is required ',

  ACCOUNT_TYPE: 'Account Type*',
  INVALID_ACCOUNT_TYPE: 'Invalid Account Type',
  REQUIRED_ACCOUNT_TYPE: 'Account Type is required',

  BANK_NAME: 'Bank Name*',
  INVALID_BANK_NAME: 'Invalid Bank Name',
  REQUIRED_BANK_NAME: 'Bank name is required',

  ACC_NO: 'Account Number*',
  INVALID_ACC_NO: 'Invalid Accout Number',
  REQUIRED_ACC_NO: 'Account Number is required',

  ACC_HOLDER_NAME: 'Account Holder Name',
  INVALID_ACC_HOLDER_NAME: 'Invalid Account Holder Name',
  REQUIRED_ACC_HOLDER_NAME: 'Account Holder Name is required',


  IFSC_CODE: 'IFSC Code*',
  INVALID_IFSC_CODE: 'Invalid IFSC Code',
  REQUIRED_IFSC_CODE: 'IFSC Code is required',
};

export const PRE_DISBURSAL_DOCUMENT_CONST = {
  HEADER: 'Pre Disbursal Documents',
  BUTTON_TITLE_SAVE: 'Save',
  BUTTON_TITLE_CANCEL: 'Cancel',
  SECURITY_PDC: 'Security PDCs',
  DOWN_PAYMENT: 'Down Payment Receipt',
  PROFORMA_INVOICE: 'Proforma Invoice',
  INSURANCE_COPY: 'Insurance Copy',
  KLI_FORM: 'KLI Form',
  OTHER_DOCUMENT: 'Other Document',
  TAKE_PHOTO: "Take Photo",
  UPLOAD_PHOTO: "Upload PDF",
  KLI_SAVE: "Save",
  MANDATORY_NAME: 'Document Name is mandatory.',
  VALID_NAME: 'Invalid Document.',
  PLACEHOLDER_NAME: "Document Name",
  BUTTON_TITLE_NEXT: 'Next',
  BUTTON_TITLE_LOAN_SUMMARY: 'Loan Summary'
}

export const POST_DISBURSAL_DOCUMENT_CONST = {
  HEADER: 'Post Disbursal Documents',
  BUTTON_TITLE_SAVE: 'Save',
  BUTTON_TITLE_CANCEL: 'Cancel',
  SECURITY_PDC: 'Security PDCs',
  DOWN_PAYMENT: 'Down Payment Receipt*',
  PROFORMA_INVOICE: 'Proforma Invoice*',
  INSURANCE_COPY: 'Insurance Copy*',
  KLI_FORM: 'KLI Form',
  OTHER_DOCUMENT: 'Other Document',
  VEHICLE_DETAILS: 'Vehicle Details*',
  BUTTON_TITLE_LOAN_SUMMARY: 'Loan Summary',
  BUTTON_TITLE_SUBMIT: 'Submit',
  SUBMITTODISBURSEMENT: 'Submit to Disbursement',
  COMMENT: 'Comment',
  TAKE_PHOTO: "Take Photo",
  UPLOAD_PHOTO: "Upload PDF",
  REGISTRATIONNUMBER: 'Vehicle Registration Number*',
  VEHICLECHASSIS: 'Vehicle Chassis Number*',
  VEHICLEENGINE: 'Vehicle Engine Number*',
  MANDATORY_REGISTRAION: 'Vehicle Registration Number is mandatory',
  VALID_REGISTRATION: 'Invalid Vehicle Registration Number',
  MANDATORY_CHASSIS: 'Vehicle Chassis Number is mandatory ',
  VALID_CHASSIS: 'Invalid Vehicle Chassis Number',
  MANDATORY_ENGINE: 'Vehicle Engine Number is mandatory',
  VALID_ENGINE: 'Invalid Vehicle Engine Numbers',
  PLACEHOLDER_NAME: "Document Name",
}

export const REPAYMENT_DETAILS_CONST = {
  HEADER: 'Repayment Details',
  BUTTON_TITLE_SAVE: 'Save',
  BUTTON_TITLE_LOAN_SUMMARY: 'Loan Summary',
  SUBMITTODISBURSEMENT: 'Submit to Disbursement',
  BUTTON_TITLE_SUBMIT: 'Submit',
  COMMENT: 'Comments',
  COUNT: 'Count of PDCs',
  CHEQUE: 'Cheque',
  VALID_COUNT: 'Invalid count of PDCs',
  MANDATORY_COUNT: 'Mandatory count of PDCs',
  VALID_CHEQUE: 'Invalid cheque number',
  MANDATORY_CHEQUE: 'Mandatory cheque number',
  VALID_UMRN: 'Invalid UMRN number',
  MANDATORY_UMRN: 'Mandatory UMRN number',
  PLACEHOLDER_NACHSTATUS: 'NACH Status'
}

export const STATES = [
  { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
  { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
  { value: 'Assam', label: 'Assam' },
  { value: 'Bihar', label: 'Bihar' },
  { value: 'Chattisgarh', label: 'Chattisgarh' },
  { value: 'Goa', label: 'Goa' },
  { value: 'Gujarat', label: 'Gujarat' },
  { value: 'Haryana', label: 'Haryana' },
  { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
  { value: 'Jammu & Kashmir', label: 'Jammu & Kashmir' },
  { value: 'Jharkhand', label: 'Jharkhand' },
  { value: 'Karnataka', label: 'Karnataka' },
  { value: 'Kerala', label: 'Kerala' },
  { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
  { value: 'Maharashtra', label: 'Maharashtra' },
  { value: 'Manipur', label: 'Manipur' },
  { value: 'Meghalaya', label: 'Meghalaya' },
  { value: 'Mizoram', label: 'Mizoram' },
  { value: 'Nagaland', label: 'Nagaland' },
  { value: 'Orissa', label: 'Orissa' },
  { value: 'Punjab', label: 'Punjab' },
  { value: 'Rajasthan', label: 'Rajasthan' },
  { value: 'Sikkim', label: 'Sikkim' },
  { value: 'Tamil Nadu', label: 'Tamil Nadu' },
  { value: 'Telangana', label: 'Telangana' },
  { value: 'Tripura', label: 'Tripura' },
  { value: 'Uttarakhand', label: 'Uttarakhand' },
  { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
  { value: 'West Bengal', label: 'West Bengal' },
  { value: 'Andaman & Nicobar', label: 'Andaman & Nicobar' },
  { value: 'Chandigarh', label: 'Chandigarh' },
  { value: 'Dadra and Nagar Haveli', label: 'Dadra and Nagar Haveli' },
  { value: 'Daman & Diu', label: 'Daman & Diu' },
  { value: 'Delhi', label: 'Delhi' },
  { value: 'Lakshadweep', label: 'Lakshadweep' },
  { value: 'Pondicherry', label: 'Pondicherry' },
]